name: ml-pipeline

on:
  push:
    paths:
      - 'scripts/**'
      - 'data/**'
      - 'models/**'
      - '.github/**'
      - 'requirements.txt'
  pull_request:


jobs:
  ml-pipeline:
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run train_model.py with MLflow logging
        run: |
          python train_model.py

      - name: Run assumption check
        run: |
          python run_assumption_checks.py

      - name: upload model and data artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-data
          path: |
            models/lin_reg.pkl
            data/processed_test_data.csv
      
      - name: upload mlflow tracking folder
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: |
            mlruns/
